spring.application.name=backend
server.port=8080
spring.servlet.multipart.max-file-size=50MB
spring.servlet.multipart.max-request-size=50MB
app.cors.allowed-origins=*

spring.mail.host=smtp.gmail.com
spring.mail.port=587
spring.mail.username=tsuhasgamer@gmail.com
spring.mail.password=uaffjuusuojfpsil
spring.mail.properties.mail.smtp.auth=true
spring.mail.properties.mail.smtp.starttls.enable=true
